language: haskell
branches:
  only:
  - source
env:
  global:
  - secure: KOMME8RshDgt7013KKe4fuHEh3txtJyPofv+b3+ZqSclsklzpbfL9rke5s7xu3BBEU/QgC0qk0YFHC64luzdSEbL2l44iRtGL/J4dUsKzRak7VfJwg5K2p+HRCwwjexYUPOGGT7F+lPF3H25l8bb84mOcrAL5SsDFdB0DZzq0Hw=
ghc:
- 7.6
install:
#- wget http://joeyeremondi.github.io/Hakyll-sandbox/hakyll-sandbox.tar.gz
#- tar -zxf ./hakyll-sandbox.tar.gz 
#- cabal sandbox init
#- travis_retry sudo apt-get install pandoc
- cabal install -j hakyll
- ghc --make site.hs
before_script:
- cd _bin
- git checkout gh-pages
- git pull origin gh-pages
- cd ..
script: yes | cp ./site ./_bin/site.bin
after_script:
- cd _bin
- git status
- git add site.bin
- git config --global user.email "joey@eremondi.com"
- git config --global user.name "JoeyEremondi"
- git commit -m "snapshot $(date '+%m/%d/%y %H:%M')"
- git push "$HAKYLL_EXEC_URL" gh-pages >/dev/null 2>&1
- cd ..
